### ISSUE TITLE
How to save the newsave_model and error in the import part of getresponse,get_pridected_value , get_diesese_practions from bot.py

### ISSUE THREAD

**Issue by Varun-2510** [Durgesh63/HealthCare_ChatBot#7]
Traceback (most recent call last):
  File "c:\Users\Acer\Downloads\HealthCare_ChatBot-master\Health_Care_App.py", line 9, in <module>
    from bot import getresponse,get_pridected_value , get_diesese_practions
  File "c:\Users\Acer\Downloads\HealthCare_ChatBot-master\bot.py", line 31, in <module>
    ners = pk.load(open('C:/Users/Acer/Downloads/HealthCare_ChatBot-master/newsave_model','rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/Acer/Downloads/HealthCare_ChatBot-master/newsave_model'

**Comment by Durgesh63** [comment]
Try to train the model :

STEP 1 :
from transformers import pipeline
PRETRAINED = "raynardj/ner-disease-ncbi-bionlp-bc5cdr-pubmed"
ners = pipeline(task="ner",model=PRETRAINED, tokenizer=PRETRAINED)

STEP 2 :
import pickle as pk
pk.dump( ner,open('/newsave_model", 'wb'))

------------------- Or -------------------------------
Please take a look at/reference this file --->
https://github.com/Durgesh63/HealthCare_ChatBot/blob/master/modeltraing_googleclob.ipynb


--------------------------------------------------- or ---------------------------------------------------------
You can also connect me on email by durgeshmaurya0998@gmail.com
